# theme: jekyll-theme-cayman  # Or another GitHub default theme
# theme: jekyll-theme-primer
# theme: jekyll-theme-minimal
# theme: jekyll-theme-midnight
# theme: jekyll-theme-dinky
# theme: jekyll-theme-hacker
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-slate
theme: jekyll-theme-tactile
# theme: jekyll-theme-time-machine

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

title: "Empowering Enterprises with Domain-Driven Design"
description: "Bookmark this to keep an eye on my project updates!"

include: ["_pages"]

defaults:
  - scope:
      path: "_pages"
    values:
      layout: single
      sidebar:
        nav: "main"

