theme: jekyll-theme-cayman  # Or another GitHub default theme

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

title: "Empowering Enterprises with Domain-Driven Design"
description: "Bookmark this to keep an eye on my project updates!"

include: ["_pages"]

defaults:
  - scope:
      path: "_pages"
    values:
      layout: single
      sidebar:
        nav: "main"

