remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme # Ensure GitHub Pages loads the theme

title: Empowering Enterprises with Domain-Driven Design
description: Bookmark this to keep an eye on my project updates!
