theme: jekyll-theme-minimal # Confirmed working theme
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
title: "Empowering Enterprises with Domain-Driven Design"
description: "Bookmark this to keep an eye on my project updates!"
include: ["_pages"]
defaults:
  - scope:
      path: "_pages"
    values:
      layout: single
      sidebar:
        nav: "main"
minimal_mistakes_skin: "default"  # Options: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
author:
  name: "Jan Honinckx"
  bio: "Domain-Driven Design Expert"
  location: "Belgium"
  links:

