# theme: jekyll-theme-minimal
# remote_theme: "mmistakes/minimal-mistakes"
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0" 

minimal_mistakes_skin: "default"
sidebar:
  nav: "main"
  search: true
  
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

title: Empowering Enterprises with Domain-Driven Design
 
description: Bookmark this to keep an eye on my project updates!

include: ["_pages"]

defaults:
  - scope:
      path: "_pages"
    values:
      layout: single
      sidebar:
        nav: "main"
sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
